server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/tigeryam_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet:
        login-username: druid
        login-password: druid